<?php
/// remove several codes generated by wordpress

/// emoji
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'wp_print_styles', 'print_emoji_styles', 10 );
add_filter( 'wpcf7_load_js', '__return_false' );
add_filter( 'wpcf7_load_css', '__return_false' );

/// oEmbed
remove_action( 'wp_head', 'rest_output_link_wp_head' );
remove_action( 'wp_head', 'wp_oembed_add_discovery_links' );
remove_action( 'wp_head', 'wp_oembed_add_host_js' );

/// EditURI
remove_action( 'wp_head', 'rsd_link' );

/// wlwmanifest
remove_action( 'wp_head', 'wlwmanifest_link' );

/// generator
remove_action( 'wp_head', 'wp_generator' );

/// shortlink
remove_action( 'wp_head', 'wp_shortlink_wp_head' );
?>